"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import type { SigningCertificate } from "@/lib/api/auth";
import { CertificateUploadDialog } from "./certificate-upload-dialog";

export function SigningCertificatesSection({
  certificates,
  onMakeDefault,
  onRemove,
  onTimestampServerSave,
  onUpload,
  timestampServerUrl,
}: {
  certificates: SigningCertificate[];
  onMakeDefault: (name: string) => Promise<void>;
  onRemove: (name: string) => Promise<void>;
  onTimestampServerSave: (value: string) => Promise<void>;
  onUpload: (file: File, name: string, password: string) => Promise<void>;
  timestampServerUrl: string;
}) {
  const [loadedAt] = useState(() => Date.now());
  const [pending, setPending] = useState<string | null>(null);
  async function change(
    name: string,
    operation: (name: string) => Promise<void>,
  ) {
    setPending(name);
    try {
      await operation(name);
    } catch (error) {
      toast.error("Certificate update failed", {
        description:
          error instanceof Error ? error.message : "Please try again",
      });
    } finally {
      setPending(null);
    }
  }
  return (
    <section
      className="mt-10 flex flex-col gap-4"
      aria-label="Signing identities"
    >
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-normal">
            Signing identities
          </h2>
          <p className="mt-2 max-w-xl text-sm text-muted-foreground">
            One identity is active for new documents. Uploading a replacement
            does not change it. Previously signed documents retain their
            original certificates.
          </p>
        </div>
        <CertificateUploadDialog onUpload={onUpload} />
      </div>
      <div className="relative overflow-x-auto rounded-xl bg-card ring-1 ring-border">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b bg-muted/50">
              <th className="p-4">Identity</th>
              <th className="p-4">Expires</th>
              <th className="p-4">Status</th>
              <th className="p-4">
                <span className="sr-only">Actions</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {certificates.map((certificate) => {
              const active =
                certificate.is_active ?? certificate.status === "default";
              const expired =
                !!certificate.valid_to &&
                new Date(certificate.valid_to).getTime() <= loadedAt;
              return (
                <tr key={certificate.name} className="border-b last:border-0">
                  <td className="max-w-80 p-4">
                    <p className="font-medium">{certificate.name}</p>
                    <p
                      className="truncate text-muted-foreground"
                      title={certificate.subject ?? undefined}
                    >
                      {certificate.subject ?? "Certificate unavailable"}
                    </p>
                    <p
                      className="mt-1 truncate font-mono text-xs text-muted-foreground"
                      title={certificate.fingerprint_sha256 ?? undefined}
                    >
                      {certificate.fingerprint_sha256}
                    </p>
                  </td>
                  <td className="whitespace-nowrap p-4">
                    {certificate.valid_to
                      ? new Date(certificate.valid_to).toLocaleDateString()
                      : "Unavailable"}
                  </td>
                  <td className="p-4">
                    {active ? "Active" : "Inactive"}
                    {expired ? " · Expired" : ""}
                  </td>
                  <td className="p-4">
                    <div className="flex justify-end gap-2">
                      {!active ? (
                        <>
                          <Button
                            size="sm"
                            variant="outline"
                            disabled={pending !== null || expired}
                            onClick={() =>
                              void change(certificate.name, onMakeDefault)
                            }
                            aria-label={`Activate ${certificate.name}`}
                          >
                            Activate
                          </Button>
                          {certificate.name !==
                          "Signa Self-Host Autogenerated" ? (
                            <Button
                              size="sm"
                              variant="ghost"
                              disabled={pending !== null}
                              onClick={() =>
                                void change(certificate.name, onRemove)
                              }
                              aria-label={`Remove ${certificate.name}`}
                            >
                              Remove
                            </Button>
                          ) : null}
                        </>
                      ) : null}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <TimestampServerForm
        key={timestampServerUrl}
        onSave={onTimestampServerSave}
        timestampServerUrl={timestampServerUrl}
      />
    </section>
  );
}

function TimestampServerForm({
  onSave,
  timestampServerUrl,
}: {
  onSave: (value: string) => Promise<void>;
  timestampServerUrl: string;
}) {
  const [value, setValue] = useState(timestampServerUrl);
  const [pending, setPending] = useState(false);
  return (
    <form
      className="mt-4 max-w-xl"
      onSubmit={async (event) => {
        event.preventDefault();
        setPending(true);
        try {
          await onSave(value);
        } finally {
          setPending(false);
        }
      }}
    >
      <Field>
        <FieldLabel htmlFor="timestamp-server-url">
          Trusted timestamp service
        </FieldLabel>
        <div className="flex gap-3">
          <Input
            id="timestamp-server-url"
            value={value}
            onChange={(event) => setValue(event.target.value)}
            placeholder="https://tsa.example.com"
            disabled={pending}
          />
          <Button
            type="submit"
            disabled={pending || value.trim() === timestampServerUrl.trim()}
          >
            {pending ? "Validating…" : "Save"}
          </Button>
        </div>
        <FieldDescription>
          Use your approved RFC 3161 service. Its CA chain must be configured by
          the server administrator. Multiple fallback URLs can be separated with
          commas.
        </FieldDescription>
      </Field>
    </form>
  );
}
