import { ApiProperty } from '@nestjs/swagger';
import { IsIn, IsOptional, IsString } from 'class-validator';

export type OAuthAuthProvider = 'google';

export class OAuthStartDto {
  @ApiProperty({
    description:
      'Auth surface that initiated the OAuth flow. This is kept in state for auditability; both modes create or reuse the same Signa session.',
    enum: ['login', 'register'],
    example: 'login',
    required: false,
  })
  @IsOptional()
  @IsIn(['login', 'register'])
  mode?: 'login' | 'register';
}

export class OAuthStartResponseDto {
  @ApiProperty({
    description:
      'Provider authorization URL. Redirect the browser here to continue OAuth.',
    example:
      'https://accounts.google.com/o/oauth2/v2/auth?client_id=...&response_type=code',
  })
  url!: string;

  @ApiProperty({
    description:
      'Signed state value generated by Signa. The frontend stores it in sessionStorage and compares it with the returned query value before completing the callback.',
    example: 'eyJwcm92aWRlciI6Imdvb2dsZSJ9.Vc4q...',
  })
  state!: string;
}

export class OAuthCallbackDto {
  @ApiProperty({
    description: 'Authorization code returned by the OAuth provider.',
    example: '4/0AbUR2VN...',
  })
  @IsString()
  code!: string;

  @ApiProperty({
    description:
      'State query parameter returned by the provider. It must match the signed state generated by Signa.',
    example: 'eyJwcm92aWRlciI6Imdvb2dsZSJ9.Vc4q...',
  })
  @IsString()
  state!: string;
}
