import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { PDFDocument } from 'pdf-lib';
import { Repository } from 'typeorm';
import { StorageAttachment } from '../storage/entities/storage-attachment.entity';
import { StorageBlob } from '../storage/entities/storage-blob.entity';
import { StorageService } from '../storage/storage.service';
import { AccountsService } from '../accounts/accounts.service';
import { AccountConfig } from '../accounts/entities/account-config.entity';
import { PdfiumProcessingService } from '../pdf-processing/pdfium-processing.service';
import { PdfSignatureService } from '../pdf-signatures/pdf-signature.service';
import { Submitter } from '../submitters/entities/submitter.entity';
import { Template } from '../templates/entities/template.entity';
import { CompletedDocument } from './entities/completed-document.entity';
import { CompletedSubmitter } from './entities/completed-submitter.entity';
import { DocumentGenerationEvent } from './entities/document-generation-event.entity';
import { SubmissionEvent } from './entities/submission-event.entity';
import { Submission } from './entities/submission.entity';
import { SubmissionDocumentsService } from './submission-documents.service';
import { SubmissionPdfGeneratorService } from './submission-pdf-generator.service';

type MockRepository<T extends object> = Partial<
  Record<keyof Repository<T>, jest.Mock>
>;

function createRepository<T extends object>(): MockRepository<T> {
  return {
    create: jest.fn((input: Partial<T>) => input),
    exists: jest.fn().mockResolvedValue(false),
    findOne: jest.fn().mockResolvedValue(null),
    save: jest.fn((input: Partial<T>) => Promise.resolve(input)),
  };
}

describe('SubmissionDocumentsService', () => {
  let service: SubmissionDocumentsService;
  let completedDocuments: MockRepository<CompletedDocument>;
  let completedSubmitters: MockRepository<CompletedSubmitter>;
  let generationEvents: MockRepository<DocumentGenerationEvent>;
  let accountConfigs: MockRepository<AccountConfig>;
  let storage: jest.Mocked<
    Pick<
      StorageService,
      | 'createBlobProxyUrl'
      | 'createPdfAttachment'
      | 'deleteRecordAttachments'
      | 'findRecordAttachments'
      | 'readBlob'
    >
  >;
  let sourcePdf: Buffer;
  let storedBuffers: Buffer[];
  let pdfSignatureService: {
    getActiveCertificateName: jest.Mock;
    getTimestampServerUrl: jest.Mock;
    loadDefaultCertificate: jest.Mock;
    signPdf: jest.Mock;
  };
  let createdPdfInputs: Array<
    Parameters<StorageService['createPdfAttachment']>[0]
  >;
  let savedCompletedDocuments: Partial<CompletedDocument>[];

  beforeEach(async () => {
    sourcePdf = await buildPdfBuffer();
    storedBuffers = [];
    createdPdfInputs = [];
    savedCompletedDocuments = [];
    completedDocuments = createRepository<CompletedDocument>();
    completedSubmitters = createRepository<CompletedSubmitter>();
    generationEvents = createRepository<DocumentGenerationEvent>();
    accountConfigs = {
      ...createRepository<AccountConfig>(),
      find: jest.fn().mockResolvedValue([]),
    };
    pdfSignatureService = {
      getActiveCertificateName: jest
        .fn()
        .mockResolvedValue('Signa Self-Host Autogenerated'),
      getTimestampServerUrl: jest.fn().mockResolvedValue(null),
      loadDefaultCertificate: jest
        .fn()
        .mockRejectedValue(new Error('Signing keys are unavailable')),
      signPdf: jest.fn((input: { buffer: Buffer }) =>
        Promise.resolve({
          buffer: input.buffer,
          certificateName: 'Signa Self-Host Autogenerated',
          ltv: {
            evidenceStatus: 'missing',
            ltvRequired: false,
          },
          pdfA: {
            conversionStatus: 'disabled',
            enabled: false,
            error: null,
            level: '2b',
            required: false,
            validationStatus: 'disabled',
          },
          signatureSubFilter: 'ETSI.CAdES.detached',
          signed: true,
          timestamp: {
            attempts: [],
            embedded: false,
            required: false,
            status: 'disabled',
            tokenSha256: null,
            url: null,
          },
          timestampServerUrl: null,
        }),
      ),
    };
    storage = {
      createBlobProxyUrl: jest.fn((blob: StorageBlob) => `/files/${blob.id}`),
      createPdfAttachment: jest.fn((input) => {
        createdPdfInputs.push(input);
        storedBuffers.push(input.buffer);

        return Promise.resolve(
          createAttachment({
            id: `generated-${storedBuffers.length}`,
            name: input.name,
            recordType: input.recordType,
            recordId: input.recordId,
            blob: {
              id: `generated-blob-${storedBuffers.length}`,
              filename: input.filename,
              contentType: 'application/pdf',
              metadata: {
                ...(input.metadata ?? {}),
                sha256: `sha-${storedBuffers.length}`,
              },
            } as unknown as StorageBlob,
          }),
        );
      }),
      deleteRecordAttachments: jest.fn().mockResolvedValue(undefined),
      findRecordAttachments: jest.fn((query) => {
        if (query.recordType === 'Template') {
          return Promise.resolve([createAttachment()]);
        }

        return Promise.resolve([]);
      }),
      readBlob: jest.fn((blob: StorageBlob) => {
        void blob;
        return Promise.resolve(sourcePdf);
      }),
    };
    completedDocuments.save?.mockImplementation(
      (input: Partial<CompletedDocument>) => {
        savedCompletedDocuments.push(input);

        return Promise.resolve(input as CompletedDocument);
      },
    );

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        SubmissionDocumentsService,
        SubmissionPdfGeneratorService,
        {
          provide: getRepositoryToken(CompletedDocument),
          useValue: completedDocuments,
        },
        {
          provide: getRepositoryToken(CompletedSubmitter),
          useValue: completedSubmitters,
        },
        {
          provide: getRepositoryToken(DocumentGenerationEvent),
          useValue: generationEvents,
        },
        {
          provide: getRepositoryToken(AccountConfig),
          useValue: accountConfigs,
        },
        {
          provide: StorageService,
          useValue: storage,
        },
        {
          provide: PdfSignatureService,
          useValue: pdfSignatureService,
        },
        {
          provide: PdfiumProcessingService,
          useValue: {
            flattenPdf: jest.fn((buffer: Buffer) =>
              Promise.resolve({
                buffer,
                flattenedPages: 0,
                pageCount: 1,
              }),
            ),
          },
        },
        {
          provide: AccountsService,
          useValue: {
            getTestingAccountContext: jest
              .fn()
              .mockResolvedValue({ isTestMode: false }),
          },
        },
      ],
    }).compile();

    service = module.get<SubmissionDocumentsService>(
      SubmissionDocumentsService,
    );
  });

  it('generates pending preview PDFs with value-hash metadata', async () => {
    const submission = createSubmission({
      submitters: [createSubmitter({ values: { field_name: 'Ada' } })],
    });

    const documents = await service.getSubmissionDocuments(submission);

    expect(documents).toHaveLength(1);
    expect(storage.createPdfAttachment).toHaveBeenCalledWith(
      expect.objectContaining({
        name: 'preview_documents',
        recordType: 'Submission',
        recordId: 'submission-1',
      }),
    );
    const generatedBuffer = storedBuffers.at(0);
    const previewInput = createdPdfInputs.at(0);

    expect(typeof previewInput?.metadata?.values_hash).toBe('string');
    expect(generatedBuffer).toBeDefined();
    await expect(
      PDFDocument.load(generatedBuffer ?? Buffer.alloc(0)),
    ).resolves.toBeDefined();
    expect(pdfSignatureService.loadDefaultCertificate).not.toHaveBeenCalled();
    expect(pdfSignatureService.signPdf).not.toHaveBeenCalled();
  });

  it('generates merged previews without loading a signing key', async () => {
    const documents = await service.getSubmissionDocuments(createSubmission(), {
      merge: true,
    });

    expect(documents).toHaveLength(1);
    await expect(PDFDocument.load(storedBuffers[0])).resolves.toBeDefined();
    expect(pdfSignatureService.loadDefaultCertificate).not.toHaveBeenCalled();
    expect(pdfSignatureService.signPdf).not.toHaveBeenCalled();
  });

  it('reads cached completed documents when signing keys are unavailable', async () => {
    const submission = createSubmission({
      submitters: [
        createSubmitter({ completedAt: new Date('2026-06-20T00:00:00Z') }),
      ],
    });
    const documents = await service.getSubmissionDocuments(submission);
    storage.findRecordAttachments.mockResolvedValue(documents);
    storage.createPdfAttachment.mockClear();
    pdfSignatureService.signPdf.mockClear();
    pdfSignatureService.signPdf.mockRejectedValue(new Error('Missing key'));

    await expect(service.getSubmissionDocuments(submission)).resolves.toEqual(
      documents,
    );
    expect(storage.createPdfAttachment).not.toHaveBeenCalled();
    expect(pdfSignatureService.loadDefaultCertificate).not.toHaveBeenCalled();
    expect(pdfSignatureService.signPdf).not.toHaveBeenCalled();
  });

  it('generates completed submitter result documents and checksum records', async () => {
    const submitter = createSubmitter({
      completedAt: new Date('2026-06-20T00:00:00.000Z'),
      values: { field_name: 'Ada' },
    });
    const submission = createSubmission({ submitters: [submitter] });
    submitter.submission = submission;

    await service.processSubmitterCompletion(submitter);

    expect(completedSubmitters.save).toHaveBeenCalledWith(
      expect.objectContaining({
        accountId: 'account-1',
        submitterId: 'submitter-1',
        submissionId: 'submission-1',
      }),
    );
    const resultAttachmentInput = createdPdfInputs.find(
      (input) =>
        input.name === 'documents' &&
        input.recordType === 'Submitter' &&
        input.recordId === 'submitter-1',
    );

    expect(resultAttachmentInput).toBeDefined();
    expect(resultAttachmentInput?.filename).toBe('contract.pdf');
    expect(resultAttachmentInput?.metadata).toMatchObject({
      original_uuid: 'attachment-uuid',
    });
    expect(typeof resultAttachmentInput?.metadata?.original_sha256).toBe(
      'string',
    );
    expect(typeof resultAttachmentInput?.metadata?.values_hash).toBe('string');
    const completedDocumentInput = savedCompletedDocuments.at(0);

    expect(completedDocumentInput).toMatchObject({
      submitterId: 'submitter-1',
    });
    expect(typeof completedDocumentInput?.sha256).toBe('string');
  });

  it('does not persist completion when result document storage fails', async () => {
    storage.createPdfAttachment.mockRejectedValueOnce(
      new Error('PDF metadata inspection failed'),
    );
    const submitter = createSubmitter({
      completedAt: new Date('2026-06-20T00:00:00.000Z'),
      values: { field_name: 'Ada' },
    });
    const submission = createSubmission({ submitters: [submitter] });
    submitter.submission = submission;

    await expect(service.processSubmitterCompletion(submitter)).rejects.toThrow(
      'PDF metadata inspection failed',
    );

    expect(completedSubmitters.save).not.toHaveBeenCalled();
    expect(generationEvents.save).toHaveBeenCalledTimes(1);
    expect(generationEvents.save).toHaveBeenCalledWith(
      expect.objectContaining({
        eventName: 'start',
        submitterId: 'submitter-1',
      }),
    );
  });

  it('uses the account document filename format for completed downloads', async () => {
    accountConfigs.find?.mockResolvedValue([
      {
        key: 'document_filename_format',
        value:
          '{document.name} - {submission.submitters} - {submission.completed_at}',
      } as AccountConfig,
    ]);
    const submitter = createSubmitter({
      completedAt: new Date('2026-06-20T00:00:00.000Z'),
      email: 'ada@example.com',
      values: { field_name: 'Ada' },
    });
    const submission = createSubmission({ submitters: [submitter] });
    submitter.submission = submission;

    await service.processSubmitterCompletion(submitter);

    const resultAttachmentInput = createdPdfInputs.find(
      (input) => input.name === 'documents',
    );

    expect(resultAttachmentInput?.filename).toBe(
      'contract-ada@example.com-2026-06-20.pdf',
    );
  });

  it('generates merged completed documents when merge is requested', async () => {
    const submitter = createSubmitter({
      completedAt: new Date('2026-06-20T00:00:00.000Z'),
    });
    const submission = createSubmission({ submitters: [submitter] });
    submitter.submission = submission;

    const documents = await service.getSubmissionDocuments(submission, {
      merge: true,
    });

    expect(documents).toHaveLength(1);
    const mergedAttachmentInput = createdPdfInputs.find(
      (input) =>
        input.name === 'merged_document' &&
        input.recordType === 'Submission' &&
        input.recordId === 'submission-1',
    );

    expect(mergedAttachmentInput).toBeDefined();
    expect(typeof mergedAttachmentInput?.metadata?.values_hash).toBe('string');
    expect(savedCompletedDocuments).toContainEqual(
      expect.objectContaining({
        sha256: 'sha-2',
        submitterId: 'submitter-1',
      }),
    );
  });

  it('generates audit trails for completed submissions', async () => {
    const submitter = createSubmitter({
      completedAt: new Date('2026-06-20T00:00:00.000Z'),
    });
    const submission = createSubmission({
      submitters: [submitter],
      submissionEvents: [
        createSubmissionEvent({ eventType: 'view_form' }),
        createSubmissionEvent({ eventType: 'complete_form' }),
      ],
    });
    submitter.submission = submission;

    const url = await service.getAuditTrailUrl(submission);

    expect(url).toBe('/files/generated-blob-2');
    expect(storage.createPdfAttachment).toHaveBeenCalledWith(
      expect.objectContaining({
        name: 'audit_trail',
        recordType: 'Submission',
        recordId: 'submission-1',
      }),
    );
    expect(
      createdPdfInputs.find((input) => input.name === 'audit_trail')?.buffer
        .byteLength,
    ).toBeGreaterThan(0);
  });
});

async function buildPdfBuffer(): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  pdf.addPage([612, 792]);

  return Buffer.from(await pdf.save());
}

function createSubmission(overrides: Partial<Submission> = {}): Submission {
  return {
    id: 'submission-1',
    accountId: 'account-1',
    templateId: 'template-1',
    name: 'NDA',
    slug: 'submission-slug',
    source: 'api',
    submittersOrder: 'preserved',
    preferences: {},
    templateFields: null,
    templateSchema: null,
    templateSubmitters: null,
    variables: {},
    variablesSchema: null,
    expireAt: null,
    archivedAt: null,
    createdAt: new Date('2026-06-19T00:00:00.000Z'),
    updatedAt: new Date('2026-06-19T00:00:00.000Z'),
    template: createTemplate(),
    submitters: [],
    submissionEvents: [],
    ...overrides,
  } as Submission;
}

function createTemplate(): Template {
  return {
    id: 'template-1',
    name: 'NDA',
    fields: [
      {
        uuid: 'field_name',
        name: 'Full Name',
        type: 'text',
        submitter_uuid: 'submitter-role-1',
        areas: [
          {
            attachment_uuid: 'attachment-uuid',
            page: 0,
            x: 0.1,
            y: 0.1,
            w: 0.4,
            h: 0.04,
          },
        ],
      },
    ],
    schema: [{ attachment_uuid: 'attachment-uuid', name: 'contract' }],
    submitters: [{ name: 'First Party', uuid: 'submitter-role-1' }],
  } as Template;
}

function createSubmitter(overrides: Partial<Submitter> = {}): Submitter {
  return {
    id: 'submitter-1',
    accountId: 'account-1',
    submissionId: 'submission-1',
    uuid: 'submitter-role-1',
    slug: 'submitter-slug',
    email: 'ada@example.com',
    name: 'Ada Lovelace',
    values: {},
    metadata: {},
    preferences: {},
    completedAt: null,
    declinedAt: null,
    sentAt: null,
    openedAt: null,
    ...overrides,
  } as Submitter;
}

function createSubmissionEvent(
  overrides: Partial<SubmissionEvent> = {},
): SubmissionEvent {
  return {
    id: 'event-1',
    accountId: 'account-1',
    submissionId: 'submission-1',
    submitterId: 'submitter-1',
    eventType: 'complete_form',
    eventTimestamp: new Date('2026-06-20T00:00:00.000Z'),
    data: {},
    ...overrides,
  } as SubmissionEvent;
}

function createAttachment(
  overrides: Partial<StorageAttachment> = {},
): StorageAttachment {
  return {
    id: 'attachment-1',
    uuid: 'attachment-uuid',
    name: 'documents',
    recordType: 'Template',
    recordId: 'template-1',
    blob: {
      id: 'blob-1',
      filename: 'contract.pdf',
      contentType: 'application/pdf',
      metadata: {},
      checksum: 'source-md5',
    } as StorageBlob,
    ...overrides,
  } as StorageAttachment;
}
